### ISSUE TITLE
How can I get valid bins in bulk? like eth-uniswapv3: 0xbfd8137f7d1516d3ea5ca83523914859ec47f573

### ISSUE THREAD

**Issue by forencen** [traderjoe-xyz/joe-v2#113]
I want to cache contract data locally for high frequency calculations. But I don't have batch fetch bins.

**Comment by forencen** [comment]
like this https://etherscan.io/address/0xbfd8137f7d1516d3ea5ca83523914859ec47f573#readContract

**Comment by 0x0Louis** [comment]
Hey, we just deployed an helper contract that allows this: 0xA5c68C9E55Dde3505e60c4B5eAe411e2977dfB35 (on avax and arbitrum).
You can query the `getPopulatedBinsId` and/or `getPopulatedBinsReserves` functions and even more.
