### ISSUE TITLE
Sorting problem of `tokenX` and `tokenY` in `LBPair`

### ISSUE THREAD

**Issue by Hayden0323** [traderjoe-xyz/joe-v2#98]
https://github.com/traderjoe-xyz/joe-v2/blob/8eeb42d73b5fe473f5b65d544d27827065a83e32/src/LBFactory.sol#L362
The `tokenX` and `tokenY` in the created pair are not sorted, and I am not sure if this is a problem. In this case, it may not be possible to assume a default order when querying off-chain.

**Comment by 0x0Louis** [comment]
It is wanted because our L formula is not symmetrical, so we want the quote token to always be token tokenY.
